# Generated by Django 5.1.1 on 2024-12-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
