# Generated by Django 5.1.1 on 2024-09-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.team')),
            ],
            options={
                'indexes': [models.Index(fields=['team'], name='analysis_pl_team_id_7b930f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('played_date', models.DateTimeField(db_index=True)),
                ('input_file', models.CharField(max_length=255)),
                ('output_file', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('game_mode', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.FloatField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.map')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one_analyses', to='analysis.team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two_analyses', to='analysis.team')),
            ],
            options={
                'indexes': [models.Index(fields=['played_date'], name='analysis_an_played__56df37_idx'), models.Index(fields=['map'], name='analysis_an_map_id_056648_idx'), models.Index(fields=['game_mode'], name='analysis_an_game_mo_be298b_idx'), models.Index(fields=['team_one'], name='analysis_an_team_on_789c3a_idx'), models.Index(fields=['team_two'], name='analysis_an_team_tw_486aea_idx')],
            },
        ),
    ]
