# Generated by Django 5.1.1 on 2024-11-03 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_customanalysis_remove_analysis_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapanalysis',
            name='series_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.seriesanalysis'),
        ),
    ]
