# Generated by Django 5.1.1 on 2024-11-03 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_mapanalysis_series_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mapanalysis',
            name='unique_map_series',
        ),
        migrations.AlterField(
            model_name='mapanalysis',
            name='series_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='analysis.seriesanalysis'),
        ),
    ]
