# Generated by Django 5.1.1 on 2024-11-06 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_mapanalysis_unique_map_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customanalysis',
            name='map_analyses',
            field=models.ManyToManyField(related_name='custom_analyses', through='analysis.CustomAnalysisMapAnalysis', to='analysis.mapanalysis'),
        ),
        migrations.AlterField(
            model_name='mapanalysis',
            name='series_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='analysis.seriesanalysis'),
        ),
    ]
