# Generated by Django 5.1.1 on 2024-11-06 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_customanalysis_map_analyses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapanalysis',
            name='series_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='analysis.seriesanalysis'),
        ),
    ]
