# Generated by Django 5.1.1 on 2024-11-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_mapanalysis_series_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermapperformancehp',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='playermapperformancehp',
            name='highest_streak',
        ),
        migrations.AddField(
            model_name='playermapperformance',
            name='damage',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playermapperformance',
            name='highest_streak',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
