# Generated by Django 5.1.1 on 2024-11-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemode',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
